spring.application.name=notes_app
spring.datasource.url=jdbc:mysql://localhost:3306/notes_application?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Abhishek85&!
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.security.user.name=user
spring.security.user.password=12345